import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "kylezhao101/api/documentation",
  description: "Generated by create next app",
};

export default function DocumentationLayout({
  children, 
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className="flex px-28 pt-14">
        <Sidebar />
        <section className="ml-64 w-4/5 mb-20">
          <div className="">
            {children}
          </div>          
        </section>
      </div>
  );
}
